# Generated by Django 5.1.1 on 2025-06-01 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='token',
            field=models.JSONField(),
        ),
    ]
